# **********************
# *  General settings  *
# **********************

# You can copy the file "en_US.yml" and paste it with another name to create your custom language
# You have to change just below with the name of your custom language file to apply changes
lang: "en_US.yml"

# Database settings
database: false
database-settings:
  hostname: localhost
  port: 3306
  database_name: test_server
  username: root
  password: pass
  
# Autopurge claims
# auto-purge-checking is in minutes (every x minutes the plugin will purge the claims)
# auto-purge-time-without-login accepts this format : 5s, 5m, 5h, 5d, 5w (5 is for example)
auto-purge: true
auto-purge-checking: 60
auto-purge-time-without-login: 14d
  
# Dynmap support
dynmap-claim-border-color: FF0000
dynmap-claim-fill-color: 00FF00
dynmap-hover-text: "%claim-name% - Owner: %owner%"

# Bluemap support
bluemap-claim-border-color: 80FF0000
bluemap-claim-fill-color: 8033CC33
bluemap-hover-text: "%claim-name% - Owner: %owner%"

# Where the protection messages are displayed
# Allowed type : ACTION_BAR (default), SUBTITLE, TITLE and CHAT
protection-message: ACTION_BAR

# Worlds where claims are disabled
worlds-disabled:
- example_world

# Length max for claim name
max-length-claim-name: 16

# Length max for claim description
max-length-claim-description: 50

# Confirmation before claiming?
claim-confirmation: false

# Display particles on the borders when claiming?
claim-particles: true

# Enable/Disable the enter/leave message in the action bar
enter-leave-messages: true

# Enable/Disable the enter/leave message in the title and subtitle
enter-leave-title-messages: true

# Enable/Disable the enter/leave message in the chat
enter-leave-chat-messages: true

# Should claims with the Visitors setting disabled be displayed in /claims?
claims-visitors-off-visible: true

# Enable/Disable the economy system (sell/buy claims)
economy: true
max-sell-price: 1000000000
# If /claim is paid
claim-cost: false
# If claim cost is multiplied (for example if claim-cost-multipler = 2, first claim will be the claim-cost, 1000 for example,
# the second claim will cost 2000, the third one 4000 ..)
claim-cost-multiplier: false

# Enable/Disable the bossbar when you are in a territory
# Placeholders :
# Use %owner% for owner's name (not for protected area)
# Use %player% for player's name
# Use %name% for claim's name
bossbar: true
bossbar-settings:
  color: yellow
  protected-area-message: "§fYou are in a §eprotected area§f !"
  owner-message: "§fYou are in your territory §e%owner% §b(%name%)"
  member-message: "§fYou are in the territory of §e%owner% §b(%name%)"
  visitor-message: "§fYou're visiting the territory of §e%owner% §b(%name%)"

# If delay > 0, can the player move
# true = can move, false = cannot move
teleportation-delay-moving: false
  
# Groups settings with permissions
# 0 for infinite claims
# 0 for no delay (in seconds)
# 0 for unlimited members
# Be careful, if you set the claim radius to 0, there is a risk of lag if players claim with a too large radius
groups:
  admin:
    permission: scs.group.admin
    max-claims: 0
    max-radius-claims: 0
    teleportation-delay: 0
    max-members: 0
    claim-cost: 0
    claim-cost-multiplier: 0
  vip: # Example
    permission: scs.group.vip
    max-claims: 15
    max-radius-claims: 2
    teleportation-delay: 0
    max-members: 5
    claim-cost: 50
    claim-cost-multiplier: 2
  default:
    max-claims: 1
    max-radius-claims: 1
    teleportation-delay: 5
    max-members: 2
    claim-cost: 100
    claim-cost-multiplier: 2
    
# Players settings
# 0 for infinite claims
# 0 for no delay (in seconds)
# 0 for unlimited members
# Be careful, if you set the claim radius to 0, there is a risk of lag if players claim with a too large radius
players: {}
  # Xyness:
    # max-claims: 0
    # max-radius-claims: 0
    # teleportation-delay: 0
    # max-members: 0
    # claim-cost: 0
    # claim-cost-multiplier: 0

# Enable/Disable settings, if you put "false", players cannot change this setting is their claims
status-settings:
  Build: true
  Destroy: true
  Buttons: true
  Items: true
  InteractBlocks: true
  Levers: true
  Plates: true
  Doors: true
  Trapdoors: true
  Fencegates: true
  Tripwires: true
  RepeatersComparators: true
  Bells: true
  Entities: true
  Explosions: true
  Liquids: true
  Redstone: true
  Frostwalker: true
  Firespread: true
  Teleportations: true
  Damages: true
  Visitors: true
  Pvp: true
  Monsters: true
  Weather: true

# List of default values for the settings
default-values-settings:
  Build: false
  Destroy: false
  Buttons: true
  Items: true
  InteractBlocks: false
  Levers: true
  Plates: true
  Doors: true
  Trapdoors: true
  Fencegates: true
  Tripwires: true
  RepeatersComparators: true
  Bells: true
  Entities: false
  Explosions: false
  Liquids: false
  Redstone: false
  Frostwalker: false
  Firespread: false
  Teleportations: false
  Damages: false
  Visitors: false
  Pvp: true
  Monsters: true
  Weather: true

# List of blocked containers for the settings "Interact with blocks"
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
blocked-interact-blocks:
- FURNACE
- BLAST_FURNACE
- ANVIL
- BREWING_STAND
- CHISELED_BOOKSHELF
- COMPOSTER
- DISPENSER
- DROPPER
- ENCHANTING_TABLE
- HOPPER
- JUKEBOX
- STONECUTTER
- BARREL
- BEACON
- CRAFTING_TABLE
- SHULKER_BOX
- CHEST
- ENDER_CHEST
- TRAPPED_CHEST
- DRAGON_EGG
- RESPAWN_ANCHOR
- CAULDRON
- LAVA_CAULDRON
- WATER_CAULDRON

# List of blocked items for the settings "Use items"
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
blocked-items:
- ENDER_PEARL
- BOW
- CROSSBOW
- TRIDENT
- FLINT_AND_STEEL
- FIRE_CHARGE
- BUCKET
- WATER_BUCKET
- LAVA_BUCKET
- CHORUS_FRUIT
- FIREWORK_ROCKET
- FIREWORK_STAR
- ENDER_EYE
- FISHING_ROD
- LEAD

# List of blocked entity type for the settings "Entities"
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html
blocked-entities:
- VILLAGER
- SHEEP
- ITEM_FRAME
- GLOW_ITEM_FRAME
- ARMOR_STAND
- PAINTING
- BOAT
- MINECART