name: SimpleClaimSystem
version: 1.11.5.2
main: fr.xyness.SCS.SimpleClaimSystem
authors: [Xyness]
softdepend: [PlaceholderAPI, WorldGuard, Vault, dynmap, bluemap, pl3xmap, GriefPrevention]
api-version: 1.18
folia-supported: true
commands:
  claim:
    description: Basic claim command
    aliases: []
    permission: scs.command.claim
  claims:
    description: All claims
    aliases: []
    permission: scs.command.claims
  unclaim:
    description: Unclaim your territory
    aliases: []
    permission: scs.command.unclaim
  scs:
    description: Admin commands
    permission: scs.admin
  protectedarea:
    aliases: [parea,pa]
    description: Protected areas commands
    permission: scs.admin