name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'

    - name: Grant execute permission for Gradle Wrapper
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v1

    - name: Build with Gradle Wrapper
      run: ./gradlew clean build --info --refresh-dependencies

    - name: Publish JAR
      uses: actions/upload-artifact@v2
      with:
        name: SimpleClaimSystem
        path: build/libs/*.jar

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'

    # This step generates and submits a dependency graph to GitHub Dependency Graph service
    # Replace it with the correct action if you find one
    - name: Generate and submit dependency graph
      run: ./gradlew dependencies
